spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/movie_alarm?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false
    username: user1
    password: user1test
  profiles:
    include: oauth

management:
  endpoints:
    web:
      base-path: /application
      path-mapping:
        health: healthcheck
      exposure:
        include: health, info
  endpoint:
    health:
      show-details: always

app:
  cors:
    allowedOrigins: http://localhost:8081